#!/usr/bin/env python3
"""
gen_ssh_kexdb.py — (re)generate scanner/ssh_kexdb.py + main_scripts/ssh_kexdb.py
from an ssh-audit checkout, so the vendored MASTER_DB is a byte-faithful copy
(zero transcription drift).

ssh-audit is MIT-licensed; we keep its verdict constants + MASTER_DB verbatim and
add only a thin read-only lookup(). To resync after an ssh-audit release:

    git clone --depth 1 https://github.com/jtesta/ssh-audit /tmp/ssh-audit
    python3 tools/gen_ssh_kexdb.py --ssh-audit-src /tmp/ssh-audit/src/ssh_audit/ssh2_kexdb.py

Because we OWN this table once vendored, version it and schedule reviews — we no
longer receive ssh-audit's upstream updates automatically.
"""
from __future__ import annotations

import argparse
import re
import textwrap
from pathlib import Path

_HEADER = '''"""
ssh_kexdb.py — vendored SSH algorithm weakness database (the "content" half of
the SSH audit capability; ssh_scanner.py is the "engine" half).

This module is a FAITHFUL, VERBATIM VENDOR of ssh-audit's ``SSH2_KexDB`` verdict
constants and ``MASTER_DB`` (algorithm -> [versions, failures, warnings, infos]),
generated by tools/gen_ssh_kexdb.py directly from ssh-audit's source so there is
zero transcription drift. Only the per-thread caching machinery was dropped (we
treat the DB as immutable and read-only) and a thin ``lookup()`` with GSS wildcard
handling was added. DO NOT edit by hand — re-run the generator instead.

DATA PROVENANCE — ssh-audit (https://github.com/jtesta/ssh-audit), MIT-licensed:

    The MIT License (MIT)
    Copyright (C) 2017-2026 Joe Testa (jtesta@positronsecurity.com)
    Copyright (C) 2017 Andris Raugulis (moo@arthepsy.eu)

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction... (full MIT text: see ssh-audit LICENSE).
    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

DB entry format (per ssh-audit):
    'algorithm_name': [[version_first_appeared], [failures...], [warnings...], [infos...]]
grouped under the categories: kex / key (host key) / enc (cipher) / mac.
"""
from __future__ import annotations


'''

_FOOTER = '''

def lookup(category: str, algo: str):
    """Return (failures, warnings, infos) for one offered algorithm, or None if
    the algorithm is not in the DB (caller records it as 'unknown').

    Exact match first; then ssh-audit's GSS wildcard rule — DB keys ending in
    '-*' (e.g. 'gss-group14-sha256-*') match any offered name starting with the
    same prefix (GSS algorithms carry variable base64 data after the prefix).
    """
    cat = MASTER_DB.get(category)
    if not cat:
        return None
    entry = cat.get(algo)
    if entry is None:
        for key, e in cat.items():
            if key.endswith("-*") and algo.startswith(key[:-1]):
                entry = e
                break
    if entry is None:
        return None
    fails = entry[1] if len(entry) > 1 else []
    warns = entry[2] if len(entry) > 2 else []
    infos = entry[3] if len(entry) > 3 else []
    return fails, warns, infos
'''


def build(src_path: Path) -> str:
    lines = src_path.read_text(encoding="utf-8").splitlines()
    start = next(i for i, ln in enumerate(lines)
                 if ln.strip().startswith("FAIL_1024BIT_MODULUS ="))
    end = next(i for i, ln in enumerate(lines) if ln.strip() == "@staticmethod")
    body = textwrap.dedent("\n".join(lines[start:end]))

    out = []
    for ln in body.splitlines():
        if "DB_PER_THREAD" in ln:
            continue
        if ln.strip().startswith("# Maintains a dictionary per calling thread"):
            continue
        out.append(ln)
    body = "\n".join(out)
    body = re.sub(r"MASTER_DB:\s*Dict\[.*?\]\s*=\s*\{", "MASTER_DB = {", body)
    return _HEADER + body.rstrip() + "\n" + _FOOTER


def main() -> None:
    repo = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ssh-audit-src", required=True,
                    help="path to ssh-audit's src/ssh_audit/ssh2_kexdb.py")
    ap.add_argument("--out", action="append", default=None,
                    help="output path(s); defaults to both scanner/ and main_scripts/")
    args = ap.parse_args()

    content = build(Path(args.ssh_audit_src))
    outs = args.out or [str(repo / "scanner" / "ssh_kexdb.py"),
                        str(repo / "main_scripts" / "ssh_kexdb.py")]
    for o in outs:
        Path(o).write_text(content, encoding="utf-8")
        print("wrote", o)


if __name__ == "__main__":
    main()
