import uuid
from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Enum, ForeignKey, Integer, String, event
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin
from app.models.enums import ScanJobStatus, ScanJobType


class ScanJob(Base, TimestampMixin):
    __tablename__ = "scan_jobs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default="gen_random_uuid()"
    )
    engagement_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("engagements.id", ondelete="CASCADE"), nullable=False, index=True
    )
    job_type: Mapped[ScanJobType] = mapped_column(
        Enum(ScanJobType, name="scanjobtype"), nullable=False
    )
    status: Mapped[ScanJobStatus] = mapped_column(
        Enum(ScanJobStatus, name="scanjobstatus"), nullable=False, server_default="pending", index=True
    )
    # Human-readable label (SCN-YYMMDD-XXXXXX, see services/reference.py). Assigned
    # once at creation and never rewritten — customers quote it in tickets. Nullable
    # only so a row can be inserted before the reference is stamped; the API always
    # sets it.
    reference: Mapped[str | None] = mapped_column(
        String(24), nullable=True, unique=True, index=True)
    agent_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    result: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    # Lease for a claimed (running) job: set at claim time, renewed on each probe
    # heartbeat. The reaper requeues running jobs whose lease has expired (dead probe).
    lease_expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, index=True
    )
    # The logical job owns a monotonically increasing execution fence. A claim
    # creates a separate ScanJobAttempt and installs it as the only current
    # attempt; heartbeat and completion must present both values.
    current_attempt_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "scan_job_attempts.id",
            ondelete="SET NULL",
            deferrable=True,
            initially="DEFERRED",
            use_alter=True,
            name="fk_scan_jobs_current_attempt_id",
        ),
        nullable=True,
        index=True,
    )
    current_fence: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default="0")
    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    max_attempts: Mapped[int] = mapped_column(Integer, nullable=False, server_default="3")

    engagement: Mapped["Engagement"] = relationship(back_populates="scan_jobs", lazy="noload")


# ── reference stamping ────────────────────────────────────────────────────────
# Six routers create ScanJob rows. Stamping the reference at each call site means
# the seventh forgets, and a job with no reference is one a customer cannot quote.
# One listener covers every insert, present and future.
#
# The id is normally generated by the database (server_default gen_random_uuid),
# so it does not exist yet at this point. We assign one here instead: the
# reference is DERIVED from the id, and the migration's backfill derives it the
# same way, so new and historical rows follow one rule. Postgres still owns the
# default for any insert that bypasses the ORM.
#
# The date part uses "now" rather than created_at (also a server default, so not
# yet known). The two can differ only for an insert that straddles UTC midnight,
# which shifts a label by a day and changes nothing that is looked up.
@event.listens_for(ScanJob, "before_insert")
def _stamp_reference(_mapper, _connection, target: "ScanJob") -> None:
    if target.reference:
        return                                   # explicitly set — never overwrite
    if target.id is None:
        target.id = uuid.uuid4()
    from app.services.reference import scan_job_reference
    target.reference = scan_job_reference(target.id)
