apiVersion: v2
name: vedha
description: VEDHA AI-Powered Network VAPT Platform
type: application
version: 1.4.0
appVersion: "1.4.0"
keywords:
  - vapt
  - security
  - vedha
maintainers:
  - name: VEDHA Engineering
    email: eng@vedha.io
